### ISSUE TITLE
Couldnt find anywhere else to put this. [Request]

### ISSUE THREAD

**Issue by MajorPlayz** [Muqsit/AntiHack#2]
Am i allowed to use your code in a plugin I am making. I will give full credit, btw code looks briliant! Good plugin

**Comment by MajorPlayz** [comment]
Also may I have push acess this looks cool and I want to contibute :D

**Comment by Muqsit** [comment]
This plugin/code is not licensed meaning you can copy, paste and distribute this code without my permission.
